Creazione Trigger con variabile :NEW
CREATE OR REPLACE TRIGGER Before_Insert_Sconti
BEFORE INSERT ON SCONTI
    FOR EACH ROW
BEGIN
    :NEW.ID := ID_SCONTI_SEQ.NEXTVAL;
    :NEW.CREAZIONE := SYSDATE;
    :NEW.VALORE := 5;
    :NEW.ANNO := EXTRACT(YEAR FROM SYSDATE);
    :NEW.SCADENZA := SYSDATE + 30;
END;


INSERT INTO SCONTI(CODFIDELITY)
VALUES('67500125');

select * from SCONTI;
