--ESEMPIO DI TRIGGER INSTEAD OF
CREATE OR REPLACE TRIGGER Tr_Modifica_Vista
    INSTEAD OF UPDATE ON VW_CLIENTI_TMP
    FOR EACH ROW
BEGIN
    
    UPDATE CARDS_TEMP 
    SET ULTIMASPESA = SYSDATE,
    BOLLINI = :NEW.BOLLINI
    WHERE CODFIDELITY = :OLD.CODFIDELITY;
    
    UPDATE CLIENTI
    SET STATO = 'Attivo'
    WHERE CODFIDELITY = :NEW.CODFIDELITY;
    
END;