--Esempio Creazione Trigger BEFORE
CREATE OR REPLACE TRIGGER Tr_Sconti
BEFORE INSERT ON SCONTI
    FOR EACH ROW
BEGIN
    :NEW.ID := ID_SCONTI_SEQ.NEXTVAL;
    :NEW.CREAZIONE := SYSDATE;
    :NEW.VALORE := 5;
    :NEW.ANNO := EXTRACT(YEAR FROM SYSDATE);
    :NEW.SCADENZA := SYSDATE + 30;
END;